spring:
  application:
    name: Facility-Admin
  datasource:
    url: jdbc:postgresql://35.247.170.16:5432/travelmarketplace
    username: postgres
    password: capstonevlu
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 28645
  error:
    include-message: always
